Starting lambda 500 (GUID: 09-17-14-04-500) at 2020-09-17 21:04:59	Added object temp to s3 bucket lambda-cpp-ap-south-1
    	Start time is not provided or is in the past
Starting lambda 970 (GUID: 09-17-14-04-970) at 2020-09-17 21:04:58	Added object temp to s3 bucket lambda-cpp-ap-south-1
    	clock precision level: 3
    	Cache line size: 64 B
    	Found an address that falls on two cache lines: 0x555556ae2dbc
    	ERROR! Already past the intitial sync point, bad run for current lambda.
